server:
  port : 8080
spring:
  application:
    name: spring-cloud-gateway

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka : true


